// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user_read.sql

package data

import (
	"context"

	"github.com/google/uuid"
)

const getUserDetailByID = `-- name: GetUserDetailByID :one
SELECT id, email, first_name, last_name, mobile_number 
FROM users
WHERE id = $1
`

type GetUserDetailByIDRow struct {
	ID           uuid.UUID
	Email        string
	FirstName    string
	LastName     string
	MobileNumber *string
}

func (q *Queries) GetUserDetailByID(ctx context.Context, id uuid.UUID) (GetUserDetailByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserDetailByID, id)
	var i GetUserDetailByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.MobileNumber,
	)
	return i, err
}
